/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'dsilva' at '7/8/17 9:59 PM' with Gradle 2.12
 *
 * @author dsilva, @date 7/8/17 9:59 PM
 */
class Library {

  boolean someLibraryMethod() {
    true
  }

}
