/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'dsilva' at '7/8/17 9:59 PM' with Gradle 2.12
 *
 * @author dsilva, @date 7/8/17 9:59 PM
 */

import org.junit.Test

class LibraryTest {

  @Test
  void someLibraryMethodShouldReturnTrue() {
    assert true == new Library().someLibraryMethod()
  }

}
